#configurar el cliente de supabase
SUPABASE_URL = "https://beryfdwrzvykxrnnshxa.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlcnlmZHdyenZ5a3hybm5zaHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2Nzc3MTUsImV4cCI6MjA0ODI1MzcxNX0.4gCYexJCUYQHEWYj2J5CceKSNvBXqC3SxwNT8fBE9cU"